name: Integration test for k8s-bake-v1
on:
   pull_request:

jobs:
   run-integration-test:
      name: Validate release and main branch
      strategy:
         matrix:
            os: [windows-latest, ubuntu-latest, macos-latest]
      runs-on: ${{ matrix.os }}
      steps:
         - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
           name: Checkout branch

         - name: Install npm packages
           run: |
              npm install --legacy-peer-deps

         - name: Install ncc
           run: npm i -g @vercel/ncc

         - name: Build
           run: ncc build src/run.ts -o lib

         - name: Bake using Helm on ${{ matrix.os }}
           uses: ./
           with:
              renderEngine: 'helm'
              helmChart: './testResources/Helm/HelmCharts'
              helm-version: 'latest'
              silent: 'false'
              namespace: 'namespaceExample'
              overrideFiles: './testResources/Helm/values.yaml'
              overrides: |
                 serviceName:aks-helloworld-test
           id: helm-bake

         - name: Validate created manifest ${{ matrix.os }}
           uses: Azure/k8s-lint@v3
           with:
              manifests: ${{ steps.helm-bake.outputs.manifestsBundle }}

         - name: Bake using Helm with semver range on ${{ matrix.os }}
           uses: ./
           with:
              renderEngine: 'helm'
              helmChart: './testResources/Helm/HelmCharts'
              helm-version: '^3.10.0'
              releaseName: 'semver-test-release'
              silent: 'false'
              namespace: 'semver-namespace'
              overrideFiles: './testResources/Helm/values.yaml'
              overrides: |
                 replicaCount:3
              arguments: '--debug'
           id: helm-semver-bake

         - name: Validate created manifest with semver helm ${{ matrix.os }}
           uses: Azure/k8s-lint@v3
           with:
              manifests: ${{ steps.helm-semver-bake.outputs.manifestsBundle }}

         - name: Executing latest changes on ${{ matrix.os }}
           uses: ./
           with:
              renderEngine: 'kompose'
              dockerComposeFile: './testResources/Kompose/docker-compose.yml'
              kompose-version: 'latest'
           id: kompose-bake

         - name: validate created manifest ${{ matrix.os }}
           uses: Azure/k8s-lint@v3
           with:
              manifests: ${{ steps.kompose-bake.outputs.manifestsBundle }}

         - name: Bake using Kustomize on ${{ matrix.os }}
           uses: ./
           with:
              renderEngine: 'kustomize'
              kustomizationPath: './testResources/Kustomize'
              kubectl-version: 'latest'
              silent: 'false'
           id: kustomize-bake

         - name: Validate created manifest ${{ matrix.os }}
           uses: Azure/k8s-lint@v3
           with:
              manifests: ${{ steps.kustomize-bake.outputs.manifestsBundle }}

         - name: Bake using Kustomize with arguments on ${{ matrix.os }}
           uses: ./
           with:
              renderEngine: 'kustomize'
              kustomizationPath: './testResources/Kustomize'
              kubectl-version: 'latest'
              arguments: '--load-restrictor=LoadRestrictionsNone'
           id: kustomize-args-bake

         - name: Validate created manifest with arguments ${{ matrix.os }}
           uses: Azure/k8s-lint@v3
           with:
              manifests: ${{ steps.kustomize-args-bake.outputs.manifestsBundle }}
